// Generated by https://quicktype.io

export interface Event {
  id: number;
  title: string;
  slug: string;
  date_of_event_start: string;
  date_of_event_end: string;
  date_of_registration_to_event: string;
  set_of_participants: boolean;
  is_active: boolean;
  filter_scope_product_export: string;
  description: string;
  image: string;
  created: string;
  category_of_event: CategoryOfEvent;
  organizer_of_event: OrganizerOfEvent;
  form_of_holding: CategoryOfEvent;
  country: CategoryOfEvent[];
}

export interface CategoryOfEvent {
  id: number;
  title: string;
  slug: string;
  description?: string;
}

export interface OrganizerOfEvent {
  id: number;
  title: string;
  slug: string;
  short_title: string;
  link_for_statement: string;
  phone_number: string;
  email: string;
  short_description: string;
  is_active: boolean;
}
