// Generated by https://quicktype.io

export interface Resolution {
  id: number;
  res_number: string;
  res_title: string;
  date_of_res: string;
  slug: string;
  application_deadline: null | string;
  short_description: string;
  document_list: string;
  how_to_get_support: string;
  information_about_res: string;
  file: null | string;
  is_active: boolean;
  mosporm: boolean;
  exported: boolean;
  requirements_full_test: string;
  scope_product_export: FilterApplicationDeadline;
  size_of_enterprise: FilterApplicationDeadline;
  grants_and_loands: FilterApplicationDeadline;
  moscow_or_rf: FilterApplicationDeadline;
  filter_application_deadline: FilterApplicationDeadline;
  industry_supported: any[];
  support_measures: FilterApplicationDeadline[];
  organizer_of_resolution: OrganizerOfResolution[];
}

export interface FilterApplicationDeadline {
  id: number;
  title: string;
  slug: string;
  short_description: string;
  is_active: boolean;
}

export interface OrganizerOfResolution {
  id: number;
  title: string;
  slug: string;
  short_title: string;
  link_for_statement: string;
  phone_number: string;
  email: string;
  short_description: string;
  is_active: boolean;
}
